//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace ObslugaMagazynuLib.Towary
{
    public class Towar : TowarAbstract
    {
        public Towar() { }

        public Towar(string n, double c, int v)
        {
            Nazwa = n;
            Cena = c;
            Vat = v;
            Id = 0;
        }

        public Towar(string n, double c, int v, string j, string nk, double s, int i)
            : this(n, c, v)
        {
            Jm = j;
            Nr_kat = nk;
            Stan = s;
            Id = i;
        }


        public Towar(string n, double c, int v, string j, string nk, double sm, double s, double mm, int m, int i, Grupa g)
            : this(n, c, v)
        {
            Jm = j;
            Nr_kat = nk;
            Stan_min = sm;
            Stan = s;
            Min_marza = mm;
            Magazyn = m;
            Id = i;
            Grupa = g;
        }

        public Towar(int i) : base(i) { }

        

    }
}

