//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ObslugaMagazynuLib.Magazyn;
using ObslugaMagazynuLib;

namespace ObslugaMagazynuLib.Towary{
	public abstract class TowarAbstract
	{
        protected string nazwa;
        protected string jm;
        protected string nr_kat;
        protected double stan_min;
        protected double stan;
        protected double cena;
        protected int vat;
        protected double min_marza;
        protected Grupa grupa;
        protected int magazyn;
        protected int id;
        protected string type;

        protected bool saveFlag = false;

        public TowarAbstract() { }

        public TowarAbstract(int i)
        {
            ListaTowarow lista = ListaTowarow.Instance;
            TowarAbstract result = lista.Find(delegate(TowarAbstract t){
                return (t.Id == i) ? true : false;
            });
            if (result != null)
            {
                Nazwa = result.Nazwa;
                Jm = result.Jm;
                Nr_kat = result.Nr_kat;
                Stan_min = result.Stan_min;
                Stan = result.Stan;
                Cena = result.Cena;
                Vat = result.Vat;
                Min_marza = result.Min_marza;
                Grupa = result.Grupa;
                Magazyn = result.Magazyn;
                Id = result.Id;
                Type = result.Type;
            }
        }

		public virtual string Nazwa
		{
            get
            {
                return nazwa;
            }
            set
            {
                nazwa = value;
            }
		}

		public virtual string Jm
		{
            get
            {
                return jm;
            }
            set
            {
                jm = value;
            }
		}

		public virtual string Nr_kat
		{
            get
            {
                return nr_kat;
            }
            set
            {
                nr_kat = value;
            }
		}

		public virtual double Stan_min
		{
            get
            {
                return stan_min;
            }
            set
            {
                stan_min = value;
            }
		}

		public virtual double Stan
		{
            get
            {
                return stan;
            }
            set
            {
                stan = value;
            }
		}

		public virtual double Cena
		{
            get
            {
                return cena;
            }
            set
            {
                cena = value;
            }
		}

		public virtual int Vat
		{
            get
            {
                return vat;
            }
            set
            {
                vat = value;
            }
		}

		public virtual double Min_marza
		{
            get
            {
                return min_marza;
            }
            set
            {
                min_marza = value;
            }
		}

		public virtual Grupa Grupa
		{
            get
            {
                return grupa;
            }
            set
            {
                if (value is Grupa)
                {
                    if (value.Id != 0)
                    {
                        grupa = value;
                    }
                    else
                    {
                        grupa = new Grupa();
                    }         
                }
            }
		}

        public virtual int Magazyn
		{
            get
            {
                return magazyn;
            }
            set
            {
                magazyn = value;
            }
		}

		public virtual int Id
		{
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
		}

        public virtual string Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }
        }

        public virtual void PowiazGrupe(Grupa g)
        {
            Grupa = g;
        }

        public virtual void MarkToSave()
        {
            saveFlag = true;
        }

        public virtual void SetSaved()
        {
            saveFlag = false;
        }

        public override string ToString()
        {
            return Nazwa;
        }

	}
}

