//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ObslugaMagazynuLib.Towary;

namespace ObslugaMagazynuLib.Dokumenty
{
    public class Elements //: ListAbstract<Element>
    {
        public List<TowarAbstract> _towarList = new List<TowarAbstract>();

    }
}
